FLASK_APP=app.py

DATABASE_URL=
CONFIG_ENV=
REDIS_URL=redis://localhost:6379/1

SECRET_KEY=
JWT_SECRET_KEY=

MAILGUN_DOMAIN=
MAILGUN_API_KEY=
MAILGUN_FROM_EMAIL=

VOD_SOURCE_BUCKET_NAME=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=