"""empty message

Revision ID: 3850b2adbcb6
Revises: c40e2ac3226d
Create Date: 2021-02-04 02:26:06.259095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3850b2adbcb6'
down_revision = 'c40e2ac3226d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('profile_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'profile_image_url')
    # ### end Alembic commands ###
