"""empty message

Revision ID: 5ebde834c7a6
Revises: 6b9844a87984
Create Date: 2021-02-11 02:03:35.956478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebde834c7a6'
down_revision = '6b9844a87984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clip_data', 'swipe_engagements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip_data', sa.Column('swipe_engagements', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
