"""empty message

Revision ID: 6b9844a87984
Revises: 3850b2adbcb6
Create Date: 2021-02-10 23:50:09.613128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9844a87984'
down_revision = '3850b2adbcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clip_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('share_clicks', sa.Integer(), nullable=True),
    sa.Column('map_clicks', sa.Integer(), nullable=True),
    sa.Column('swipe_engagements', sa.Integer(), nullable=True),
    sa.Column('deliveroo_clicks', sa.Integer(), nullable=True),
    sa.Column('uber_eats_clicks', sa.Integer(), nullable=True),
    sa.Column('just_eat_clicks', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('fk_clip_data_clip_id_clips')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clip_data_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clip_data'))
    )
    op.add_column('relevances', sa.Column('favourite', sa.Boolean(), nullable=True))
    op.add_column('relevances', sa.Column('profile_views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relevances', 'profile_views')
    op.drop_column('relevances', 'favourite')
    op.drop_table('clip_data')
    # ### end Alembic commands ###
