"""empty message

Revision ID: c40e2ac3226d
Revises: 
Create Date: 2021-01-08 02:34:13.708080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c40e2ac3226d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_locations_device_id_devices', 'locations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_locations_user_id_users'), 'locations', 'users', ['user_id'], ['id'])
    op.drop_column('locations', 'device_id')
    op.add_column('relevances', sa.Column('rating', sa.Float(), nullable=False))
    op.add_column('relevances', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_relevances_rating'), 'relevances', ['rating'], unique=False)
    op.drop_index('ix_relevances_preference_rating', table_name='relevances')
    op.drop_constraint('fk_relevances_device_id_devices', 'relevances', type_='foreignkey')
    op.create_foreign_key(op.f('fk_relevances_user_id_users'), 'relevances', 'users', ['user_id'], ['id'])
    op.drop_column('relevances', 'device_id')
    op.drop_column('relevances', 'preference_rating')
    op.drop_index('ix_devices_device_id', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relevances', sa.Column('preference_rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('relevances', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_relevances_user_id_users'), 'relevances', type_='foreignkey')
    op.create_foreign_key('fk_relevances_device_id_devices', 'relevances', 'devices', ['device_id'], ['id'])
    op.create_index('ix_relevances_preference_rating', 'relevances', ['preference_rating'], unique=False)
    op.drop_index(op.f('ix_relevances_rating'), table_name='relevances')
    op.drop_column('relevances', 'user_id')
    op.drop_column('relevances', 'rating')
    op.add_column('locations', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_locations_user_id_users'), 'locations', type_='foreignkey')
    op.create_foreign_key('fk_locations_device_id_devices', 'locations', 'devices', ['device_id'], ['id'])
    op.drop_column('locations', 'user_id')
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_devices_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_devices')
    )
    op.create_index('ix_devices_device_id', 'devices', ['device_id'], unique=False)
    # ### end Alembic commands ###
